CREATE TABLE CITIES(
    ID int NOT NULL,
    CITY VARCHAR(20),
    STATE VARCHAR(20),
    PRIMARY KEY (ID)
);

CREATE TABLE WAREHOUSES(
    WAREHOUSE_ID int NOT NULL,
    WNAME VARCHAR(30),
    LOCATION VARCHAR(20),
    EXTRA_CONTEXT json,
    PRIMARY KEY (WAREHOUSE_ID)
);

CREATE TABLE STORES(
    STORE_ID int NOT NULL,
    STORE_NAME VARCHAR(20),
    LOCATION_CITY VARCHAR(20),
    PRIMARY KEY (STORE_ID)
);

CREATE TABLE CUSTOMER(
    CNO int NOT NULL, 
    CNAME VARCHAR(50),
    ADDR VARCHAR(50),
    CU_CITY VARCHAR(20),
    PRIMARY KEY (CNO)
);

CREATE TABLE ORDERS(
    ONO int NOT NULL,
    ODATE DATE,
    PRIMARY KEY (ONO)
);

CREATE TABLE ITEMS(
    ITEMNO int NOT NULL,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2),
    PRIMARY KEY (ITEMNO)
); 

ALTER TABLE WAREHOUSES
ADD FOREIGN KEY(CID) REFERENCES CITIES (ID)

ALTER TABLE STORES
ADD FOREIGN KEY(WID) REFERENCES WAREHOUSES (WAREHOUSE_ID)

ALTER TABLE ORDERS
ADD FOREIGN KEY(CNO) REFERENCES CUSTOMER (CNO)

CREATE TABLE ITEMSORDERS(
    IOID int NOT NULL,
    ITEMNO int,
    ONO int,
    PRIMARY KEY (IOID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS (ITEMNO),
    FOREIGN KEY (ONO) REFERENCES ORDERS (ONO)
); 

CREATE TABLE STORESITEMS(
    ID int NOT NULL,
    SID int,
    ITEMNO int,
    PRIMARY KEY (ID),
    FOREIGN KEY (ITEMNO) REFERENCES ITEMS (ITEMNO),
    FOREIGN KEY (SID) REFERENCES STORES (STORE_ID)
); 